
FROM enactordev-on.azurecr.io/enactorstandardbase/lin/is:BASE-IMAGE-TAG-TOKEN

LABEL Description="IMAGE-CUSTOMER-NAME-TOKEN - Identity Server" 
LABEL Vendor="Enactor" 
LABEL StandardVersion="BUILD-IMAGE-TAG-TOKEN"

ADD root /

CMD ["/enactor/shared/tomcat/bin/run.sh"]
