# escape=`
FROM enactordev-on.azurecr.io/enactorstandardbase/win/ws:BASE-IMAGE-TAG-TOKEN

LABEL Description="IMAGE-CUSTOMER-NAME-TOKEN - Web Shop" 
LABEL Vendor="Enactor" 
LABEL StandardVersion="BUILD-IMAGE-TAG-TOKEN"

ADD root c:\

CMD ["C:\\enactor\\shared\\tomcat\\bin\\run.bat", "run"]

