
FROM enactordev-on.azurecr.io/enactorstandardbase/lin/pdp:BASE-IMAGE-TAG-TOKEN

LABEL Description="IMAGE-CUSTOMER-NAME-TOKEN - PDP" 
LABEL Vendor="Enactor" 
LABEL StandardVersion="BUILD-IMAGE-TAG-TOKEN"

COPY root /

CMD ["/enactor/app/scripts/run.sh]
