---
version: "3.4"

networks:
  enactor-stack-overlay:
    external:
      name: enactor-stack-overlay

volumes:
  enactor-data-ems-home:
    external: true
    name: enactor-data-ems-home
  db-data-em:
    external: true
    name: db-data-em
  enactor-data-omp-home:
    external: true
    name: enactor-data-omp-home

secrets:
  allow_root_remote_login:
    file: ../resources/allow-root-remote-login.sql

services:
  mariadb-em:
    image: enactordev-on.azurecr.io/enactor-mariadb:latest
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: []
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
    environment:
      - MYSQL_ROOT_PASSWORD=enactor
      - MYSQL_DATABASE=enactorem
    ports:
      - target: 3306
        published: 3306
        mode: ingress
    networks:
      - enactor-stack-overlay
    volumes:
      - db-data-em:/var/lib/mysql
    secrets:
      - source: allow_root_remote_login
        target: /docker-entrypoint-initdb.d/allow-root-remote-login.sql
        mode: 0555
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"


  em-services:
    image: enactordev-on.azurecr.io/enactorstandard/lin/ems:2.7.747.RC2.29.866
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: []
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 240s
        monitor: 60s
        max_failure_ratio: 0.3
    env_file:
      - ../envs/common.env
      - ../envs/common-em.env
      - ../envs/ems.env
    ports:
      - target: 39833
        published: 39833
        mode: ingress
      - target: 52243
        published: 52243
        mode: ingress
    networks:
      - enactor-stack-overlay
    volumes:
      - enactor-data-ems-home:/enactor/app/home
    logging:
      driver: "json-file"
      options:
        max-size: "1024k"
        max-file: "3"
